[profile.default]
src = "src"
test = "test"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./script/config/"},
    { access = "read", path = "./out/"}
]

[profile.default.fmt]
wrap_comments = true

[profile.default.rpc_endpoints]
custom = "${RPC_URL}"
ethereum = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
goerli = "https://eth-goerli.g.alchemy.com/v2/${ALCHEMY_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_KEY}"
optimism = "${OPTIMISM_URL}"
arbitrum = "${ARBITRUM_URL}"


[profile.build]
via-ir = true
test = "/dev/null"
script = "/dev/null"


[profile.script]
src = "/dev/null"
test = "/dev/null"


[profile.test-slow]
via-ir = false

[profile.test-slow.fuzz]
runs = 10000
max_test_rejects = 500000

[profile.test-slow.invariant]
runs = 64
depth = 2048


[profile.test-fast]
via-ir = false

[profile.test-fast.fuzz]
runs = 256
max_test_rejects = 65536

[profile.test-fast.invariant]
runs = 16
depth = 256

[profile.checker]
test = 'certora/checker'
fs_permissions = [{access = "read", path= "./"}]
match_contract = 'Checker'
